# Generated by Django 3.0.8 on 2020-09-10 07:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Cli_Run', models.IntegerField(primary_key=True, serialize=False)),
                ('Cli_Nom', models.CharField(max_length=20)),
                ('Cli_Ap_Pat', models.CharField(max_length=30)),
                ('Cli_Ap_Mat', models.CharField(max_length=30)),
                ('Cli_Email', models.CharField(blank=True, max_length=50)),
                ('Cli_Tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('Est_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Est_Nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('Mar_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Mar_nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaRepuesto',
            fields=[
                ('Mar_nom', models.CharField(max_length=50)),
                ('Mar_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('Rep_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Rep_Nom', models.CharField(max_length=30)),
                ('Rep_Can', models.IntegerField()),
                ('Rep_Mar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc.MarcaRepuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('Tip_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Tip_nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('Veh_Id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Veh_Mod', models.CharField(max_length=20)),
                ('Veh_Agno', models.IntegerField()),
                ('Veh_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc.Cliente')),
                ('Veh_Mar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc.Marca')),
                ('Veh_Tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc.Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('Tra_Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Tra_Des', models.CharField(max_length=500)),
                ('Tra_Fechainicio', models.DateTimeField(default=datetime.datetime.now)),
                ('Tra_Fechafin', models.DateTimeField(blank=True)),
                ('Tra_Est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc.Estado')),
                ('Tra_Vehic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc.Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Tra_rep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trep_Cant', models.IntegerField()),
                ('Trep_Repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc.Repuesto')),
                ('Trep_Trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc.Trabajo')),
            ],
        ),
    ]
