# Generated by Django 3.0.8 on 2020-09-11 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tra_rep',
            name='id',
        ),
        migrations.AlterField(
            model_name='tra_rep',
            name='Trep_Trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sc.Trabajo'),
        ),
    ]
